#!/bin/bash
# Wordlist
# Example:  hashcat -a 0 -m 0 example.hash example.dict
source functions.sh
default_scripts="/$HOME/Crack_Master"

define_default_parameters
define_colors

# List available sessions
echo -e "${GREEN}Available sessions:${NC}"
restore_files=$(find "$default_restorepath" -name "*.restore" -exec basename {} \; | sed 's/\.restore$//')
if [ -z "$restore_files" ]; then
    echo "No restore files found..."
else
    echo "$restore_files"
fi

# Restore session if requested
echo -e "\n${RED}Restore? (Enter restore file name or leave empty):${NC}"
read restore_file_input
restore_session "$restore_file_input"

# Prompt user inputs
echo -e "${MAGENTA}Enter session name (press Enter to use default '$default_session'):${NC}"
read session_input
session=${session_input:-$default_session}

echo -e "${MAGENTA}Available Wordlists in $default_wordlists:${NC} "
ls "$default_wordlists"
echo -e "${MAGENTA}Enter Wordlist (press Enter to use default '$default_wordlist'):${NC}"
read wordlist_input
wordlist=${wordlist_input:-$default_wordlist}

# Print the hashcat command
echo -e "${GREEN}Restore >>${NC} $default_restorepath/$session"
echo -e "${GREEN}Command >>${NC} hashcat --session="$session" -m 22000 hash.hc22000 -a 0 -w 4 --outfile-format=2 -o plaintext.txt "$default_wordlists/$wordlist""

# Execute hashcat with the specified wordlist
hashcat --session="$session" -m 22000 hash.hc22000 -a 0 -w 4 --outfile-format=2 -o plaintext.txt "$default_wordlists/$wordlist"

# Save successful settings
save_settings "$session" "$default_wordlists" "$wordlist" ""

# Save logs
mkdir logs
echo "$session" > session.txt
echo -e "$status" > status.txt
mv session.txt logs
mv status.txt logs
mv plaintext.txt logs

